---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: aashrit
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: server
        image: nginx:1.17
        volumeMounts:
          - name: helloworld
            mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: "128M"
          limits:
            cpu: 100m
            memory: "256M"
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
      volumes:
      - name: helloworld
        configMap:
          name: helloworld
          items:
          - key: body
            path: index.html