apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: aashrit
  labels:
    app: helloworld
spec:
  type: LoadBalancer
  ports:
  - name: helloworld-http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld